version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - storage_data:/var/www/storage
    networks:
      - agricultura_network

  nginx:
    build:
      context: .
      dockerfile: Dockerfile
      target: nginx
    restart: unless-stopped
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - storage_data:/var/www/storage
    depends_on:
      - app
    networks:
      - agricultura_network

  db:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: agricultura
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_PASSWORD: password
      MYSQL_USER: agricultura
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - agricultura_network

volumes:
  dbdata:
  storage_data:

networks:
  agricultura_network:
    driver: bridge
