version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - storage_data:/var/www/storage
    networks:
      - agricultura_network

  nginx:
    image: nginx:alpine
    restart: unless-stopped
    volumes:
      - ./public:/var/www/public:ro
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - agricultura_network

  db:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: agricultura
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_PASSWORD: password
      MYSQL_USER: agricultura
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - agricultura_network

volumes:
  dbdata:
  storage_data:

networks:
  agricultura_network:
    driver: bridge
